In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("house-prices-tp.csv")
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.07151,0.0,4.49,0.0,0.449,6.121,56.8,3.7476,3.0,247.0,18.5,395.15,8.44,22.2
1,0.08265,0.0,13.92,0.0,0.437,6.127,18.4,5.5027,4.0,289.0,16.0,396.90,8.58,23.9
2,0.12816,12.5,6.07,0.0,0.409,5.885,33.0,6.4980,4.0,345.0,18.9,396.90,8.79,20.9
3,0.08873,21.0,5.64,0.0,0.439,5.963,45.7,6.8147,4.0,243.0,16.8,395.56,13.45,19.7
4,0.11432,0.0,8.56,0.0,0.520,6.781,71.3,2.8561,5.0,384.0,20.9,395.58,7.67,26.5

In [3]:
#vista de los datos en general
df.sample(5)
#paneo general del df
df.info()
#Analizamos cantidad de na en las diferentes columnas
display(df.isna().sum())
#Analizamos duplicados
display(df.duplicated().sum())
#analisis sobre los valores de los datos
display(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 556 entries, 0 to 555
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     533 non-null    float64
 1   ZN       534 non-null    float64
 2   INDUS    541 non-null    float64
 3   CHAS     533 non-null    float64
 4   NOX      532 non-null    float64
 5   RM       535 non-null    float64
 6   AGE      532 non-null    float64
 7   DIS      541 non-null    float64
 8   RAD      528 non-null    float64
 9   TAX      538 non-null    float64
 10  PTRATIO  528 non-null    float64
 11  B        534 non-null    float64
 12  LSTAT    534 non-null    float64
 13  MEDV     535 non-null    float64
dtypes: float64(14)
memory usage: 60.9 KB

CRIM       23
ZN         22
INDUS      15
CHAS       23
NOX        24
RM         21
AGE        24
DIS        15
RAD        28
TAX        18
PTRATIO    28
B          22
LSTAT      22
MEDV       21
dtype: int64

np.int64(0)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,533.000000,534.000000,541.000000,533.000000,532.000000,535.000000,532.000000,541.000000,528.000000,538.000000,528.000000,534.000000,534.000000,535.000000
mean,5.845517,13.197175,11.218725,0.090056,0.560050,6.291839,67.632303,3.944102,9.699379,409.575089,18.429904,347.806040,13.028092,22.746809
std,13.828631,24.902981,6.942021,0.286531,0.119472,0.782403,28.461925,2.255689,8.684495,167.689379,2.194759,99.636208,7.579972,9.491452
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.084470,0.000000,5.130000,0.000000,0.453000,5.875500,42.275000,2.112100,4.000000,279.000000,17.000000,369.530000,7.150000,16.750000
50%,0.315330,0.000000,9.690000,0.000000,0.538000,6.208000,76.500000,3.340107,5.000000,335.000000,19.000000,390.815000,11.465000,21.200000
75%,4.871410,20.000000,18.100000,0.000000,0.643986,6.638500,93.825000,5.400700,23.632660,666.000000,20.200000,395.890000,17.205000,26.300000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [4]:
df["RAD"].unique()

array([ 3.        ,  4.        ,  5.        ,  1.        ,  8.        ,
       24.        , 10.5548915 ,  7.        ,  2.        ,         nan,
        6.        , 14.63832996, 17.0001503 ,  6.85012281, 22.06951085,
        1.30712763, 17.16456963, 10.16870119, 21.90077626, 15.23957943,
        4.8117484 , 19.26689099,  3.05654826, 23.51021334, 17.11018134,
       18.17750289,  2.40242419,  4.52856858,  2.57361455, 22.32831295,
       14.19552773, 20.41690761])

In [5]:
display(df.isna().sum())
#observamos que hay 506 registros totalmente integros, y los demas tienden a tener na, pensamos en quedarnos dropear registros con 5 o mas
#nulos debido a que sino estariamos creando sinteticamente el dataset
display(df.isna().sum(axis=1).value_counts().sort_index())
#observamos un truncamiento dentro del dataset a 50
display(df['MEDV'].value_counts())

CRIM       23
ZN         22
INDUS      15
CHAS       23
NOX        24
RM         21
AGE        24
DIS        15
RAD        28
TAX        18
PTRATIO    28
B          22
LSTAT      22
MEDV       21
dtype: int64

0     506
1       5
2       3
3      11
4       3
5       3
6       2
7       5
8       4
9       4
10      1
11      3
12      2
13      3
14      1
Name: count, dtype: int64

MEDV
50.000000    16
25.000000     8
21.700000     7
22.000000     7
23.100000     7
             ..
36.000000     1
30.800000     1
41.700000     1
36.400000     1
23.028798     1
Name: count, Length: 258, dtype: int64

In [6]:
#los valores reales son unicamente los numeros enteros, ya que logicamente, 
# no existen autopistas con numeros con coma, parecen ser filas corruptas las que contienen los valores con coma,
#  ya que las filas que no tienen na tampoco tienen valores con coma
sucias = df.isna().any(axis=1)
print(sorted(df.loc[~sucias, 'RAD'].unique()))   
print(sorted(df.loc[sucias, 'RAD'].dropna().unique()))

[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(24.0)]
[np.float64(1.3071276337271132), np.float64(2.402424185436736), np.float64(2.573614546445113), np.float64(3.056548264661834), np.float64(4.528568576401572), np.float64(4.811748400829242), np.float64(6.850122813308411), np.float64(10.1687011932127), np.float64(10.554891504036352), np.float64(14.195527728631848), np.float64(14.63832995512883), np.float64(15.239579433369125), np.float64(17.00015030082133), np.float64(17.110181340117375), np.float64(17.164569631646437), np.float64(18.177502888577678), np.float64(19.26689098525532), np.float64(20.41690761322129), np.float64(21.900776258906152), np.float64(22.069510849964647), np.float64(22.328312952252293), np.float64(23.510213342044743)]

2 cosas importantes para ver desp
targets nulos -> eliminar esos datos ya que al no tener todas las features no se pueden tampoco usar en el training
no existen los rad con coma ya que son una autopista -> clasificacion categorica
todos los nulos caen sobre las filas corruptas

---
nuestro modelo va a tender a sub-estimar los valores de las casas ya que tienen un limite de 50000, pero es preferile eso a eliminar los datos por llamarlos sinteticos o corruptos y que no tengamos un rango mas acotado o menos conocimiento sobre como predecir precios altos